- title: General
  icon: settings
  description: View and update your store details

- title: Payments
  icon: cash
  description: Enable and manage your store's payment providers

- title: Checkout
  icon: shopping-cart
  description: Customize your online checkout process

- title: Shipping and delivery
  icon: truck-delivery
  description: Manage how you ship orders to customers

- title: Taxes
  icon: tax
  description: Manage how your store charges taxes

- title: Locations
  icon: map-pin
  description: Manage the places you stock inventory, fulfill orders, and sell products

- title: Notifications
  icon: bell
  description: Manage notifications sent to you and your customers

- title: Gift cards
  icon: gift
  description: Enable Apple Wallet passes and set gift card expiry dates

- title: Files
  icon: file-invoice
  description: Upload images, videos, and documents

- title: Sales channels
  icon: chart-line
  description: Manage the channels you use to sell your products and services

- title: Plan and permissions
  icon: user
  description: View plan information and manage what staff can see or do in your store

- title: Store languages
  icon: language
  description: Manage the languages your customers can view on your store

- title: Billing
  icon: wallet
  description: Manage your billing information and view your invoices

- title: Legal
  icon: license
  description: Manage your store's legal pages