source: pages
destination: tmp

title: Tabler Admin Template
description: Premium and Open Source dashboard template with responsive and high quality UI.
github_url: https://github.com/tabler/tabler

debug: false

plugins:
- jekyll-random
- jekyll-tidy
- jekyll-timeago
- jekyll-redirect-from
- jekyll-include-cache

keep_files:
- css/ui-kit.css
- css/dark.css
- css/rtl.css
#- js/ui-kit.js

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    span:
      line_numbers: false

jekyll_tidy:
  compress_html: false
  ignore_env: development


collections:
  docs:
    output: true
  changelog:
    output: false
  components:
    output: true

defaults:
  -
    scope:
      type: pages
    values:
      layout: default
      nav-position: top
  -
    scope:
      type: docs
    values:
      layout: docs
      nav-position: top
  -
    scope:
      type: components
    values:
      layout: component


colors:
  blue:
    hex: '#206bc4'
    name: Blue
  azure:
    hex: '#45aaf2'
    name: Azure
  indigo:
    hex: '#6574cd'
    name: Indigo
  purple:
    hex: '#a55eea'
    name: Purple
  pink:
    hex: '#f66d9b'
    name: Pink
  red:
    hex: '#fa4654'
    name: Red
  orange:
    hex: '#fd9644'
    name: Orange
  yellow:
    hex: '#f1c40f'
    name: Yellow
  lime:
    hex: '#7bd235'
    name: Lime
  green:
    hex: '#5eba00'
    name: Green
  teal:
    hex: '#2bcbba'
    name: Teal
  cyan:
    hex: '#17a2b8'
    name: Cyan
  gray:
    hex: '#868e96'
    name: Gray
  dark:
    hex: '#354051'
    name: Dark

variants:
  - name: success
    icon: check
  - name: info
    icon: info
  - name: warning
    icon: alert-triangle
  - name: danger
    icon: x-octagon

button_variants:
  - name: primary
    title: Primary
  - name: secondary
    title: Secondary
  - name: success
    title: Success
  - name: info
    title: Info
  - name: warning
    title: Warning
  - name: danger
    title: Danger

socials:
  - name: facebook
    icon: brand/facebook
    title: Facebook
  - name: twitter
    icon: brand/twitter
    title: Twitter
  - name: google
    icon: brand/google
    title: Google
  - name: youtube
    icon: brand/youtube
    title: Youtube
  - name: vimeo
    icon: brand/vimeo
    title: Vimeo
  - name: dribbble
    icon: brand/dribbble
    title: Dribbble
  - name: github
    icon: brand/github
    title: Github
  - name: instagram
    icon: brand/instagram
    title: Instagram
  - name: pinterest
    icon: brand/pinterest
    title: Pinterest
  - name: vk
    icon: brand/vk
    title: VK
  - name: rss
    icon: brand/rss
    title: RSS
  - name: flickr
    icon: brand/flickr
    title: Flickr
  - name: bitbucket
    icon: brand/bitbucket
    title: Bitbucker
  - name: tabler
    icon: brand/tabler
    title: Tabler

months_short: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
months_long: ['January', 'Febuary', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
