title: Tabler
description: tabler.github.io - a responsive, flat and full featured admin template

source: src
host: 0.0.0.0

plugins:
  - jekyll-tidy
  - jekyll-toc
  - jekyll-random

exclude:
  - regenerate-images.sh
  - .editorconfig
  - buddy.yml
  - package.json
  - gulpfile.js
  - start.sh
  - Gemfile
  - Gemfile.lock
  - .git
  - .idea
  - .gitignore
  - node_modules/
  - .DS_Store
  - .sass-cache/
  - .asset-cache/
  - push-to-repo.sh
  - commits.sh
  - assets/scss/*
  - assets/plugins/**/*.scss

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: docs


markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    span:
      line_numbers: false

toc:
  min_level: 2
  max_level: 3

jekyll_tidy:
  compress_html: false
  ignore_env: development

base_color: '#467fcf'
github_url: https://github.com/tabler/tabler

author:
   name: codecalm.net
   url: https://codecalm.net

docs-menu:
  - title: Getting started
    pages: [index]
  - title: Components
    pages: [alerts, avatars, buttons, colors, cards, charts, form-components, tags, typography]

colors:
  blue: 
    hex: '#467fcf'
    name: Blue
  azure: 
    hex: '#45aaf2'
    name: Azure
  indigo: 
    hex: '#6574cd'
    name: Indigo
  purple: 
    hex: '#a55eea'
    name: Purple
  pink: 
    hex: '#f66d9b'
    name: Pink
  red: 
    hex: '#e74c3c'
    name: Red
  orange: 
    hex: '#fd9644'
    name: Orange
  yellow: 
    hex: '#f1c40f'
    name: Yellow
  lime: 
    hex: '#7bd235'
    name: Lime
  green: 
    hex: '#5eba00'
    name: Green
  teal: 
    hex: '#2bcbba'
    name: Teal
  cyan: 
    hex: '#17a2b8'
    name: Cyan
  gray: 
    hex: '#868e96'
    name: Gray
  gray-dark: 
    hex: '#343a40'
    name: Dark gray

theme-colors:
  primary: 
    hex: '#467fcf'
    name: Primary
  secondary: 
    hex: '#868e96'
    name: Secondary
  success: 
    hex: '#38c172'
    name: Success
  info: 
    hex: '#17a2b8'
    name: Info
  warning: 
    hex: '#f8b700'
    name: Warning
  danger: 
    hex: '#f90049'
    name: Danger
#  light:
#    hex: '#f8f9fa'
#    name: Light
#  dark:
#    hex: '#343a40'
#    name: Dark

color_variants:
  - name: 'Darkest'
    suffix: -darkest
  - name: 'Darker'
    suffix: -darker
  - name: 'Dark'
    suffix: -dark
  - name: 'Default'
    suffix: ''
  - name: 'Light'
    suffix: -light
  - name: 'Lighter'
    suffix: -lighter
  - name: 'Lightest'
    suffix: -lightest

social-buttons:
  facebook:
    icon: fa fa-facebook
    name: Facebook
  twitter:
    icon: fa fa-twitter
    name: Twitter
  google:
    icon: fa fa-google
    name: Google
  youtube:
    icon: fa fa-youtube
    name: Youtube
  vimeo:
    icon: fa fa-vimeo
    name: Vimeo
  dribbble:
    icon: fa fa-dribbble
    name: Dribble
  github:
    icon: fa fa-github
    name: Github
  instagram:
    icon: fa fa-instagram
    name: Instagram
  pinterest:
    icon: fa fa-pinterest
    name: Pinterest
  vk:
    icon: fa fa-vk
    name: VKontakte
  rss:
    icon: fa fa-rss
    name: RSS
  flickr:
    icon: fa fa-flickr
    name: Flickr
  bitbucket:
    icon: fa fa-bitbucket
    name: Bitbucket

google-maps-key: AIzaSyBEJy4UvF-JfcNciWlvlznyDlUckcspiD4
google-maps-url: https://maps.googleapis.com/maps/api/js?key=AIzaSyCOJwXN0eoyeFZ3cYtGzPLFw8zGhQ750Xk

theme-plugins:
  charts-c3:
    name: c3.js Charts
    files: [css, js]
  maps-google:
    name: Google Maps
    files: [css, js]
  input-mask:
    name: Input Mask
    files: [js]
#  iconfonts:
#    name: Iconfonts
#    files: [css]
#  prismjs:
#    name: Code Highlight
#    files: [css, js]
#  fullcalendar:
#    name: FullCalendar
#    files: [css, js]
#  weather:
#    name: Weather
#    files: [css]