source: src/pages
destination: tmp

keep_files:
  - css
  - js
  - img
  - dist
  - static
  - playground.html

use-iconfont: false
rtl: false

title: Tabler
description: Premium and Open Source dashboard template with responsive and high quality UI.
homepage: https://tabler.io
github-url: https://github.com/tabler/tabler
github-sponsors-url: https://github.com/sponsors/codecalm
changelog-url: https://github.com/tabler/tabler/releases
sponsor-url: https://github.com/sponsors/codecalm
preview-url: https://preview.tabler.io

mapbox-key: pk.eyJ1IjoiY29kZWNhbG0iLCJhIjoiSzRiOVJvQSJ9.BUVkTT6IYs83xSUs4H7bjQ
google-maps-key: AIzaSyAr5mRB4U1KRkVznIrDWEvZjroYcD202DI
google-maps-dev-key: AIzaSyCL-BY8-sq12m0S9H-S_yMqDmcun3A9znw
npm-package: "@tabler/core"

random-date-from: "2018-01-01"
random-date-to: "2022-01-01"

debug: false

layout-dark: false

plugins:
  - jekyll-random
  - jekyll-tidy
  - jekyll-timeago
  - jekyll-redirect-from

tabler-css-plugins:
  - tabler-flags
  - tabler-payments
  - tabler-vendors

exclude:
  - .jekyll-cache
  - redirects.json

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

jekyll_tidy:
  compress_html: false
  ignore_env: development

collections:
  docs:
    output: true

defaults:
  - scope:
      type: "pages"
      path: "*.md"
    values:
      layout: markdown
  - scope:
      type: "pages"
    values:
      layout: default
  - scope:
      type: "docs"
    values:
      layout: docs

colors:
  blue:
    class: blue
    hex: '#206bc4'
    title: Blue
  azure:
    class: azure
    hex: '#45aaf2'
    title: Azure
  indigo:
    class: indigo
    hex: '#6574cd'
    title: Indigo
  purple:
    class: purple
    hex: '#a55eea'
    title: Purple
  pink:
    class: pink
    hex: '#f66d9b'
    title: Pink
  red:
    class: red
    hex: '#fa4654'
    title: Red
  orange:
    class: orange
    hex: '#fd9644'
    title: Orange
  yellow:
    class: yellow
    hex: '#f1c40f'
    title: Yellow
  lime:
    class: lime
    hex: '#7bd235'
    title: Lime
  green:
    class: green
    hex: '#5eba00'
    title: Green
  teal:
    class: teal
    hex: '#2bcbba'
    title: Teal
  cyan:
    class: cyan
    hex: '#17a2b8'
    title: Cyan

colors-extra:
  white:
    hex: '#ffffff'
    title: White
  dark:
    hex: '#303645'
    title: Dark
  gray:
    hex: '#868e96'
    title: Gray

variants:
  - name: success
    icon: check
  - name: info
    icon: info-circle
  - name: warning
    icon: alert-triangle
  - name: danger
    icon: alert-circle

theme-colors:
  primary:
    class: primary
    title: Primary
  secondary:
    class: secondary
    title: Secondary
  success:
    class: success
    title: Success
  warning:
    class: warning
    title: Warning
  danger:
    class: danger
    title: Danger
  info:
    class: info
    title: Info
  dark:
    class: dark
    title: Dark
  light:
    class: light
    title: Light

button-states:
  - class:
    title: Normal
  - class: active
    title: Active state
  - class: disabled
    title: Disabled

socials:
  facebook:
    icon: brand-facebook
    title: Facebook
  twitter:
    icon: brand-twitter
    title: Twitter
  google:
    icon: brand-google
    title: Google
  youtube:
    icon: brand-youtube
    title: Youtube
  vimeo:
    icon: brand-vimeo
    title: Vimeo
  dribbble:
    icon: brand-dribbble
    title: Dribbble
  github:
    icon: brand-github
    title: Github
  instagram:
    icon: brand-instagram
    title: Instagram
  pinterest:
    icon: brand-pinterest
    title: Pinterest
  vk:
    icon: brand-vk
    title: VK
  rss:
    icon: rss
    title: RSS
  flickr:
    icon: brand-flickr
    title: Flickr
  bitbucket:
    icon: brand-bitbucket
    title: Bitbucket
  tabler:
    icon: brand-tabler
    title: Tabler

months-short: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
months-long: ['January', 'Febuary', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
